import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, BorderStyle, AlignmentType, WidthType } from "docx";

/**
 * DOCX Export Utility for Textify Platform by Suhas S
 * Generates structured, valid Microsoft Word (.docx) files.
 */
export const exportToDOCX = async ({
  title = "Textify Document Report",
  subtitle = "Generated by Textify - AI English Writing & Learning Platform",
  author = "Suhas S",
  content = "",
  correctedContent = "",
  stats = null,
  errors = [],
  score = null,
  filename = "Textify_Export"
}) => {
  try {
    const children = [];

    // Header Title
    children.push(
      new Paragraph({
        text: title,
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.LEFT,
        spacing: { after: 100 }
      })
    );

    // Subtitle
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: subtitle,
            italics: true,
            color: "475569",
            size: 20 // 10pt
          }),
          new TextRun({
            text: ` | Author: ${author} | Date: ${new Date().toLocaleDateString()}`,
            color: "64748B",
            size: 18
          })
        ],
        spacing: { after: 300 }
      })
    );

    // Quality Score Summary
    if (score !== null) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `Quality Score: `,
              bold: true,
              size: 24
            }),
            new TextRun({
              text: `${score} / 100`,
              bold: true,
              color: "0D9488",
              size: 26
            })
          ],
          spacing: { after: 200 }
        })
      );
    }

    // Original Text Section
    if (content) {
      children.push(
        new Paragraph({
          text: "Original / Input Text",
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 200, after: 100 }
        })
      );

      const contentParagraphs = content.split("\n").filter((p) => p.trim());
      contentParagraphs.forEach((pText) => {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: pText, size: 22 })],
            spacing: { after: 120 }
          })
        );
      });
    }

    // Corrected Output Section
    if (correctedContent) {
      children.push(
        new Paragraph({
          text: "Corrected / Improved Output",
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 100 }
        })
      );

      const correctedParagraphs = correctedContent.split("\n").filter((p) => p.trim());
      correctedParagraphs.forEach((pText) => {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: pText,
                size: 22,
                color: "0F172A"
              })
            ],
            spacing: { after: 120 }
          })
        );
      });
    }

    // Document Statistics Section
    if (stats) {
      children.push(
        new Paragraph({
          text: "Document Statistics",
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 100 }
        })
      );

      const tableRows = [
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Metric", bold: true })] })], width: { size: 50, type: WidthType.PERCENTAGE } }),
            new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Value", bold: true })] })], width: { size: 50, type: WidthType.PERCENTAGE } })
          ]
        }),
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph({ text: "Word Count" })] }),
            new TableCell({ children: [new Paragraph({ text: `${stats.words || 0}` })] })
          ]
        }),
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph({ text: "Character Count" })] }),
            new TableCell({ children: [new Paragraph({ text: `${stats.characters || 0}` })] })
          ]
        }),
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph({ text: "Sentence Count" })] }),
            new TableCell({ children: [new Paragraph({ text: `${stats.sentences || 0}` })] })
          ]
        }),
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph({ text: "Reading Time" })] }),
            new TableCell({ children: [new Paragraph({ text: `${stats.readingTime || "1 min"}` })] })
          ]
        }),
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph({ text: "Readability Rating" })] }),
            new TableCell({ children: [new Paragraph({ text: `${stats.readability || "Good"}` })] })
          ]
        })
      ];

      children.push(
        new Table({
          rows: tableRows,
          width: { size: 100, type: WidthType.PERCENTAGE }
        })
      );
    }

    // Detected Issues List
    if (errors && errors.length > 0) {
      children.push(
        new Paragraph({
          text: `Detected Errors & Suggestions (${errors.length})`,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 100 }
        })
      );

      errors.forEach((err, index) => {
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: `${index + 1}. [${err.type || "Grammar"}] `, bold: true, color: "E11D48" }),
              new TextRun({ text: `"${err.original || err.text}" → `, strike: true, color: "64748B" }),
              new TextRun({ text: `"${err.suggestion || err.replacement}"`, bold: true, color: "0D9488" }),
              new TextRun({ text: err.explanation ? ` (${err.explanation})` : "", italics: true, color: "475569" })
            ],
            spacing: { after: 100 }
          })
        );
      });
    }

    // Create Document Object
    const docObj = new Document({
      sections: [
        {
          properties: {},
          children: children
        }
      ]
    });

    const blob = await Packer.toBlob(docObj);
    const cleanFilename = filename.toLowerCase().replace(/[^a-z0-9]/g, "_");
    
    // Trigger Download
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `${cleanFilename}_textify.docx`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);

    return true;
  } catch (error) {
    console.error("Failed to generate DOCX:", error);
    throw error;
  }
};
