import jsPDF from "jspdf";

/**
 * PDF Export Utility for Textify Platform by Suhas S
 * Supports multi-page output, headers, footers, tables, and statistics.
 */
export const exportToPDF = async ({
  title = "Textify Document Report",
  subtitle = "Generated by Textify - AI English Writing & Learning Platform",
  author = "Suhas S",
  content = "",
  correctedContent = "",
  stats = null,
  errors = [],
  suggestions = [],
  score = null,
  filename = "Textify_Export"
}) => {
  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4"
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    const addHeader = (pageNum) => {
      doc.setFillColor(13, 148, 136); // Teal primary
      doc.rect(0, 0, pageWidth, 12, "F");

      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.text("TEXTIFY | AI Writing & Learning Platform", margin, 8);

      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text(`Created by Suhas S | Page ${pageNum}`, pageWidth - margin, 8, { align: "right" });
    };

    const addFooter = () => {
      doc.setDrawColor(226, 232, 240);
      doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

      doc.setTextColor(100, 116, 139);
      doc.setFontSize(8);
      doc.text("Textify Platform © Suhas S - https://www.linkedin.com/in/suhas-s-081b84335", margin, pageHeight - 6);
      doc.text(new Date().toLocaleDateString(), pageWidth - margin, pageHeight - 6, { align: "right" });
    };

    let currentPage = 1;
    addHeader(currentPage);
    addFooter();

    y = 22;

    // Document Title
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(title, margin, y);
    y += 7;

    // Subtitle
    doc.setTextColor(71, 85, 105);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(subtitle, margin, y);
    y += 10;

    // Divider
    doc.setDrawColor(203, 213, 225);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // Summary Box if score provided
    if (score !== null) {
      doc.setFillColor(240, 253, 250); // Light teal
      doc.setDrawColor(20, 184, 166);
      doc.roundedRect(margin, y, contentWidth, 18, 2, 2, "FD");

      doc.setTextColor(15, 23, 42);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(`Overall Quality Score: ${score}/100`, margin + 5, y + 7);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(51, 65, 85);
      const grade = score >= 90 ? "Excellent" : score >= 75 ? "Good" : score >= 60 ? "Fair" : "Needs Improvement";
      doc.text(`Status: ${grade} | Date: ${new Date().toLocaleDateString()}`, margin + 5, y + 13);

      y += 24;
    }

    // Helper function for adding multiline text with auto page breaking
    const printParagraph = (headerText, bodyText, bgTeal = false) => {
      if (y > pageHeight - 35) {
        doc.addPage();
        currentPage++;
        addHeader(currentPage);
        addFooter();
        y = 22;
      }

      if (headerText) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(15, 23, 42);
        doc.text(headerText, margin, y);
        y += 6;
      }

      if (!bodyText) return;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(30, 41, 59);

      const splitLines = doc.splitTextToSize(bodyText, contentWidth - (bgTeal ? 6 : 0));

      if (bgTeal) {
        const boxHeight = splitLines.length * 5 + 6;
        if (y + boxHeight > pageHeight - 20) {
          doc.addPage();
          currentPage++;
          addHeader(currentPage);
          addFooter();
          y = 22;
        }
        doc.setFillColor(248, 250, 252);
        doc.setDrawColor(226, 232, 240);
        doc.roundedRect(margin, y, contentWidth, boxHeight, 1.5, 1.5, "FD");
        y += 4;
        splitLines.forEach((line) => {
          doc.text(line, margin + 3, y);
          y += 5;
        });
        y += 6;
      } else {
        splitLines.forEach((line) => {
          if (y > pageHeight - 20) {
            doc.addPage();
            currentPage++;
            addHeader(currentPage);
            addFooter();
            y = 22;
          }
          doc.text(line, margin, y);
          y += 5;
        });
        y += 4;
      }
    };

    // Output Sections
    if (content) {
      printParagraph("Original / Input Text", content, true);
    }

    if (correctedContent) {
      printParagraph("Corrected / Improved Output", correctedContent, true);
    }

    // Key Statistics Section
    if (stats) {
      if (y > pageHeight - 45) {
        doc.addPage();
        currentPage++;
        addHeader(currentPage);
        addFooter();
        y = 22;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text("Document Analytics & Statistics", margin, y);
      y += 6;

      doc.setFillColor(241, 245, 249);
      doc.rect(margin, y, contentWidth, 22, "F");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(51, 65, 85);

      const col1 = margin + 5;
      const col2 = margin + 50;
      const col3 = margin + 105;

      doc.text(`Words: ${stats.words || 0}`, col1, y + 6);
      doc.text(`Characters: ${stats.characters || 0}`, col1, y + 12);
      doc.text(`Sentences: ${stats.sentences || 0}`, col1, y + 18);

      doc.text(`Paragraphs: ${stats.paragraphs || 1}`, col2, y + 6);
      doc.text(`Avg Sentence: ${stats.avgSentenceLength || 0} wps`, col2, y + 12);
      doc.text(`Reading Time: ${stats.readingTime || "1 min"}`, col2, y + 18);

      doc.text(`Readability: ${stats.readability || "Good"}`, col3, y + 6);
      doc.text(`Tone: ${stats.tone || "Neutral"}`, col3, y + 12);

      y += 28;
    }

    // Errors & Suggestions Section
    if (errors && errors.length > 0) {
      if (y > pageHeight - 40) {
        doc.addPage();
        currentPage++;
        addHeader(currentPage);
        addFooter();
        y = 22;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text(`Detected Issues & Corrections (${errors.length})`, margin, y);
      y += 6;

      errors.slice(0, 15).forEach((err, idx) => {
        if (y > pageHeight - 20) {
          doc.addPage();
          currentPage++;
          addHeader(currentPage);
          addFooter();
          y = 22;
        }

        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(225, 29, 72); // Red error label
        doc.text(`${idx + 1}. [${err.type || "Grammar"}] "${err.original || err.text}"`, margin, y);
        y += 4;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(15, 118, 110); // Teal correction
        doc.text(`   Suggestion: ${err.suggestion || err.replacement}`, margin, y);
        y += 4;

        if (err.explanation) {
          doc.setTextColor(71, 85, 105);
          doc.text(`   Reason: ${err.explanation}`, margin, y);
          y += 4;
        }
        y += 2;
      });
    }

    const cleanFilename = filename.toLowerCase().replace(/[^a-z0-9]/g, "_");
    doc.save(`${cleanFilename}_textify.pdf`);
    return true;
  } catch (error) {
    console.error("Failed to generate PDF:", error);
    throw error;
  }
};
